### ISSUE TITLE
下载不存在的文件导致程序退出

### ISSUE THREAD

**Issue by lwifew** [tickstep/aliyunpan#103]
**现象**：交互模式下使用`d`命令下载一不存在的文件时程序会退出交互模式，并返回一个**panic**。
**复现**：登录之后使用`d`命令下载任意不存在的文件
**复现频率**：稳定复现
**操作系统**：windows10
**使用版本**：aliyunpan version v0.1.5
**期待结果**：当下载不存在的文件时提醒文件不存在，而非直接退出交互
**详细报错信息**：
```bash
aliyunpan:来自分享 AntInAli$ d help

[0] 当前文件下载最大并发量为: 5, 下载缓存为: 64.00KB

[1] 加入下载队列: /来自分享/help
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xaf2a7d]

goroutine 37 [running]:
github.com/tickstep/aliyunpan/internal/functions/pandownload.(*DownloadTaskUnit).pluginCallback(0xc000096140, 0xcbfd2e, 0x4)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/pandownload/download_task_unit.go:354 +0x9d
github.com/tickstep/aliyunpan/internal/functions/pandownload.(*DownloadTaskUnit).OnFailed(0xc000096140, 0xc000430700)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/pandownload/download_task_unit.go:339 +0x5c
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc0002c8ab0, 0xc0002c88a0, 0xc00040e510)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:155 +0x1ed
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x85
```

**Comment by tickstep** [comment]
下个版本改下。
不过你这issue提交的真是专业🥰

**Comment by tickstep** [comment]
v0.1.5 版本已修复
