### ISSUE TITLE
ubuntu => 阿里云盘 同步时报错

### ISSUE THREAD

**Issue by baloyou** [tickstep/aliyunpan#116]
大约有300多个G的文件要上传，前100多G是成功的，后来发现网络IO没有速度，重启服务后，发现如下错误。

目前，程序已经无法正常工作(`aliyunpan sync start ...`)

```
panic: runtime error: index out of range [0] with length 0

goroutine 13 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:462 +0x21f9
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:57 +0x145a
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0xc000578000, 0xc0002c3c20)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:774 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:773 +0x30d
```

看错误信息是某个数组的索引越界？在上传过程中，我给本地文件夹复制进来新文件，这会影响上传吗？

**Comment by baloyou** [comment]
删除了同步数据库之后（sync_drive/自动生成的文件夹）之后，似乎可以重新同步。

但是否可以认为：曾经的同步记录已经丢失，需要重新上传所有文件？

上传到阿里云盘是个非常优秀的功能，希望能在文档中更多说明上传机制、过程，这样碰到问题可以先分析一下。

**Comment by tickstep** [comment]
> 删除了同步数据库之后（sync_drive/自动生成的文件夹）之后，似乎可以重新同步。
> 
> 
> 
> 但是否可以认为：曾经的同步记录已经丢失，需要重新上传所有文件？
> 
> 
> 
> 上传到阿里云盘是个非常优秀的功能，希望能在文档中更多说明上传机制、过程，这样碰到问题可以先分析一下。

这个倒不会，sync功能会对比文件，只会上传不存在的文件，已经存着网盘的不会重复上传

**Comment by tickstep** [comment]
> 大约有300多个G的文件要上传，前100多G是成功的，后来发现网络IO没有速度，重启服务后，发现如下错误。
> 
> 
> 
> 目前，程序已经无法正常工作(`aliyunpan sync start ...`)
> 
> 
> 
> ```
> 
> panic: runtime error: index out of range [0] with length 0
> 
> 
> 
> goroutine 13 [running]:
> 
> github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
> 
> 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:462 +0x21f9
> 
> github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
> 
> 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:57 +0x145a
> 
> github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0xc000578000, 0xc0002c3c20)
> 
> 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:774 +0x45
> 
> created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
> 
> 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:773 +0x30d
> 
> ```
> 
> 
> 
> 看错误信息是某个数组的索引越界？在上传过程中，我给本地文件夹复制进来新文件，这会影响上传吗？

看能不能开启debug日志，有利于分析问题

**Comment by baloyou** [comment]
> > 大约有300多个G的文件要上传，前100多G是成功的，后来发现网络IO没有速度，重启服务后，发现如下错误。
> > 目前，程序已经无法正常工作(`aliyunpan sync start ...`)
> > ```
> > 
> > panic: runtime error: index out of range [0] with length 0
> > 
> > 
> > 
> > goroutine 13 [running]:
> > 
> > github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
> > 
> > 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:462 +0x21f9
> > 
> > github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0x0, 0x0)
> > 
> > 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:57 +0x145a
> > 
> > github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc00259e000, 0xdacaf8, 0xc00055edc0, 0xc000578000, 0xc0002c3c20)
> > 
> > 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:774 +0x45
> > 
> > created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
> > 
> > 	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:773 +0x30d
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 看错误信息是某个数组的索引越界？在上传过程中，我给本地文件夹复制进来新文件，这会影响上传吗？
> 
> 看能不能开启debug日志，有利于分析问题

我下次试试收集下DEBUG，因为我删除了同步数据库，所以现在报错无法重现。

**Comment by baloyou** [comment]
> > 删除了同步数据库之后（sync_drive/自动生成的文件夹）之后，似乎可以重新同步。
> > 但是否可以认为：曾经的同步记录已经丢失，需要重新上传所有文件？
> > 上传到阿里云盘是个非常优秀的功能，希望能在文档中更多说明上传机制、过程，这样碰到问题可以先分析一下。
> 
> 这个倒不会，sync功能会对比文件，只会上传不存在的文件，已经存着网盘的不会重复上传

这是个好消息。

不过，同步盘目前最大的问题是：不知道当前的上传速度、状态，也不清楚还有哪些文件没有上传，如果报错卡住了也不知道。

**Comment by hjames1** [comment]
同样存在这个问题

**Comment by inwikipedia** [comment]
![image](https://github.com/user-attachments/assets/858f16bf-e747-44ac-a7d8-bef52736bb84)
我这边也是报错，可以直接try catch吗？

**Comment by xiaoyaofenfen** [comment]
请在新版本中继续关注，感谢反馈
