### ISSUE TITLE
上传报这个错是怎么回事呢？

### ISSUE THREAD

**Issue by jiangzhaoyong** [tickstep/aliyunpan#126]
panic: runtime error: invalid memory address or nil pointer dereference

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xabae03]

goroutine 52 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0xc000128b00, 0xc00058c200)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:354 +0xa83
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc000288810, 0xc00047a000, 0xc00059e348)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x62
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x7c`

**Comment by caixu0518** [comment]
我也遇到相同问题。求解决方法。

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xabae03]

goroutine 567 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0xc0008d28f0, 0xc0003e32c0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:354 +0xa83
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc00023ce70, 0xc00027c2a0, 0xc00014cdb0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x62
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x7c

**Comment by tickstep** [comment]
> 我也遇到相同问题。求解决方法。
> 
> 
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> 
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xabae03]
> 
> 
> 
> goroutine 567 [running]:
> 
> github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0xc0008d28f0, 0xc0003e32c0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:354 +0xa83
> 
> github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc00023ce70, 0xc00027c2a0, 0xc00014cdb0)
> 
>         /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x62
> 
> created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
> 
>         /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x7c

你开debug日志贴上来，方便定位问题

**Comment by COCONUTYA1** [comment]
[2022-7-27 18:38:55.368] add local file to db:  {"fileName":"xl.meta","fileSize":35437,"fileType":"file","createdAt":"2022-07-22 22:30:04","updatedAt":"2022-07-22 22:30:04","fileExtension":".meta","sha1Hash":"","path":"/mnt/SSD/share/images/youdaonote-images/WEBRESOURCEdae5fb3d4b94549d98a493df0b404494.png/xl.meta","scanTimeAt":"2022-07-27 03:38:55","scanStatus":"normal"}
[2022-7-27 18:38:55.594] do request url: https://api.aliyundrive.com/v2/file/list
[2022-7-27 18:38:55.608] do request url: https://api.aliyundrive.com/v2/file/list
[2022-7-27 18:38:55.725] do request url: https://api.aliyundrive.com/v2/file/list
[2022-7-27 18:38:55.887] file action task： {"action":"create_pan_folder","status":"create","localFile":{"fileName":"WEBRESOURCE64bc1fee62bb2a30e2d81e9d8327269a.png","fileSize":3,"fileType":"folder","createdAt":"2022-07-22 22:30:02","updatedAt":"2022-07-22 22:30:02","fileExtension":".png","sha1Hash":"","path":"/mnt/SSD/share/images/youdaonote-images/WEBRESOURCE64bc1fee62bb2a30e2d81e9d8327269a.png","scanTimeAt":"2022-07-27 03:37:01","scanStatus":"normal"},"panFile":null,"localFolderPath":"/mnt/SSD/share/images","panFolderPath":"/TrueNAS_Backup/images","statusUpdateTime":"","driveId":"46819","useInternalUrl":false,"downloadRange":null,"downloadBlockSize":1048576,"uploadRange":null,"uploadEntity":null,"uploadPartSeq":0,"uploadBlockSize":10485760}
[2022-7-27 18:38:55.887] 创建云盘文件夹: /TrueNAS_Backup/images/youdaonote-images/WEBRESOURCE64bc1fee62bb2a30e2d81e9d8327269a.png
[2022-7-27 18:38:55.887] do request url: https://api.aliyundrive.com/adrive/v2/file/createWithFolders
[2022-7-27 18:38:55.889] add local file to db:  {"fileName":"xl.meta","fileSize":63965,"fileType":"file","createdAt":"2022-07-22 22:30:04","updatedAt":"2022-07-22 22:30:04","fileExtension":".meta","sha1Hash":"","path":"/mnt/SSD/share/images/youdaonote-images/WEBRESOURCEdf80c330e60f98c7d0b728c16cfaefd4.png/xl.meta","scanTimeAt":"2022-07-27 03:38:55","scanStatus":"normal"}
[2022-7-27 18:38:56.064] 创建云盘文件夹成功: /TrueNAS_Backup/images/youdaonote-images/WEBRESOURCE64bc1fee62bb2a30e2d81e9d8327269a.png
[2022-7-27 18:38:56.083] do request url: https://api.aliyundrive.com/v2/file/list
[2022-7-27 18:38:56.195] do request url: https://api.aliyundrive.com/v2/file/list
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xacae2a]

goroutine 384 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).deletePanFile(0xc000373740, 0xdacaf8, 0xc000420ec0, 0x2c5, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:613 +0x3aa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc000373740, 0xdacaf8, 0xc000420ec0, 0xc0006741e0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:135 +0xb65
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func4(0xc000373740, 0xdacaf8, 0xc000420ec0, 0xc0000b0280, 0xc00011ddd0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:834 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:833 +0x63b
root@truenas[~]#
