### ISSUE TITLE
UploadFilePart中chunkPos越界

### ISSUE THREAD

**Issue by gangxie112** [tickstep/aliyunpan#185]
没太仔细看代码，好像这个可能越界？
func (p *PanClientProxy) UploadFilePart(userId, pathStr string, offset int64, buffer []byte) (int, error) {
	fus, err := p.UploadFileCache(userId, pathStr)
	if err != nil {
		return 0, err
	}
	fus.mutex.Lock()
	defer fus.mutex.Unlock()

	if fus.fileWritePos != offset {
		// error
		return 0, fmt.Errorf("file write offset position mismatch")
	}

	// write buffer to chunk buffer
	uploadCount := 0
	for _, b := range buffer {
		fus.chunkBuffer[fus.chunkPos] = b <<<------

	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc0004e3040, 0xdbf8a0, 0xc00052bb00)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
2022/11/06 22:53:58 http: panic serving 127.0.0.1:41144: runtime error: index out of range [10485760] with length 10485760
goroutine 3198 [running]:
net/http.(*conn).serve.func1(0xc004312e60)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0xc60220, 0xc000c53a10)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/tickstep/aliyunpan/internal/webdav.(*PanClientProxy).UploadFilePart(0xc0001f65a0, 0xc00f92f700, 0x5, 0xc00f92a900, 0x76, 0xa00000, 0xc012af6000, 0x8000, 0x8000, 0x0, ...)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/webdav/pan_client_proxy.go:670 +0xdb5
github.com/tickstep/aliyunpan/internal/webdav.(*WebDavFile).Write(0xc0003bd040, 0xc012af6000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/webdav/webdav_file.go:346 +0x8d
io.copyBuffer(0x7f05a24233a0, 0xc0003bd040, 0x7f05a24233c0, 0xc000d92fe0, 0xc012af6000, 0x8000, 0x8000, 0xdc2df0, 0xc0003bd040, 0x0)
	/usr/local/go/src/io/io.go:425 +0x21c
io.Copy(...)
	/usr/local/go/src/io/io.go:382
golang.org/x/net/webdav.(*Handler).handlePut(0xc0003d9240, 0xdbd6a8, 0xc0033efc00, 0xc00f95ad00, 0x0, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/webdav/webdav.go:271 +0x28e
golang.org/x/net/webdav.(*Handler).ServeHTTP(0xc0003d9240, 0xdbd6a8, 0xc0033efc00, 0xc00f95ad00)
	/Users/tickstep/Applications/go/pkg/mod/golang.org/x/net@v0.0.0-20210614182718-04defd469f4e/webdav/webdav.go:57 +0x287
github.com/tickstep/aliyunpan/internal/webdav.(*Config).ServeHTTP(0xc000520240, 0xdbd6a8, 0xc0033efc00, 0xc010f84500)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/webdav/webdav.go:149 +0x77e
net/http.serverHandler.ServeHTTP(0xc00056e000, 0xdbd6a8, 0xc0033efc00, 0xc010f84500)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc004312e60, 0xdbf8a0, 0xc004135fc0)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go

**Comment by gangxie112** [comment]
使用的是镜像v2.0.3

**Comment by xiaoyaofenfen** [comment]
新版本上传已经优化很多，请在新版本中继续关注，感谢反馈
