### ISSUE TITLE
报告一个运行时panic

### ISSUE THREAD

**Issue by Hotwill** [tickstep/aliyunpan#232]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x1198d9a]

goroutine 173148 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc003d5a2a0, 0x149f8f8, 0xc0003fd200, 0x13d06f8, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc003d5a2a0, 0x149f8f8, 0xc0003fd200, 0xc000174000, 0xc000220630)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x4a
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d
```

版本： v0.2.5

**Comment by alienwow** [comment]
同上，我在群晖docker运行也一样的错误

2023/02/14 10:51:01 http: panic serving 172.11.80.59:38036: runtime error: invalid memory address or nil pointer dereference

**Comment by xiaoyaofenfen** [comment]
逻辑上做了判空处理，下个版本再观察下

**Comment by dreamfly32** [comment]
> 逻辑上做了判空处理，下个版本再观察下

麻烦更新下docker镜像
