### ISSUE TITLE
文件上传报错了

### ISSUE THREAD

**Issue by LiJie298** [tickstep/aliyunpan#240]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x16ddd5a]

goroutine 65 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc00060e000, 0x19de738, 0xc000296280, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc00060e000, 0x19de738, 0xc000296280, 0xc000148460, 0xc00020c090)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d

**Comment by thelittlefox** [comment]
阿里云盘好像更改加密协议了

**Comment by pkking** [comment]
同样的问题，mark

**Comment by LiJie298** [comment]
下载了最新版本（aliyunpan-v0.2.6）后等到了解决，可以尝试一下！
