### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by kesry** [tickstep/aliyunpan#242]
阿里云盘登录成功:  Unknown
aliyunpan:/ Unknown$ upload /home/app/data/note.bask.20230216.tgz doc.bak

[0] 当前文件上传最大并发量为: 10, 上传分片大小为: 10.00MB
警告: 上传文件, 获取云盘路径 /doc.bak 错误, invalid X-Device-Id
[1] 加入上传队列: /home/app/data/note.bask.20230216.tgz
[1] 2023-02-16 13:50:23 准备上传: /home/app/data/note.bask.20230216.tgz => /doc.bak/note.bask.20230216.tgz
[1] 2023-02-16 13:50:23 正在检测和创建云盘文件夹: /doc.bak
[1] 2023-02-16 13:50:23 文件上传结果：  耗时 1秒

上传结束, 时间: 1秒, 数据总量: 0B
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5ef094]

goroutine 67 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0x40004d0160, 0x400027df00)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:369 +0x7b4
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0x4000245200, 0x40001a10b0, 0x4000112d08)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x5c
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x6c

**Comment by lafi2333** [comment]
我也遇到了同样的问题

**Comment by Leepay** [comment]
我把要被上传的文件路径加引号后解决了
