### ISSUE TITLE
使用upload命令时报错：invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by MN2yFii** [tickstep/aliyunpan#244]
命令：`upload --ow --retry 10 /path/to/local/dir /apps/uploads`
数据大小：约5000个文件，最大单文件约800m，合计120g

使用v0.2.5上传文件的时候偶尔会出现下面日志所示的错误，有时出现有时又不会。v0.2.1也有这个问题，但很旧的v0.1.3则没报过这个错误，其他版本没逐一测试。命令在交互界面中输入。没启用js插件。架构是树莓派3 aarch64。查日志没有oom。

```bash
[9] 2023-02-16 14:45:23 正在检测和创建云盘文件夹: /apps/uploads/encrypted/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rHHdeGockILw4yHPb7fQXSU--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3r6QxykJYRKwp5y6vG3wITGk--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rkOhOP.xFabd7ObpsvR8s2k--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rvyp5A5LYNgNw2DNk0IwyAU--
[2023-2-16 14:45:00.176] do request url: https://api.aliyundrive.com/v2/file/list
[2023-2-16 14:45:00.176] file path cache hit:  /apps/uploads/encrypted/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rHHdeGockILw4yHPb7fQXSU--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3r6QxykJYRKwp5y6vG3wITGk--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rkOhOP.xFabd7ObpsvR8s2k--/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3rvyp5A5LYNgNw2DNk0IwyAU--
[2023-2-16 14:45:00.176] do request url: https://api.aliyundrive.com/v2/file/list
[2023-2-16 14:45:00.176] [1] 2023-02-16 14:45:23 准备结束, 准备耗时 0秒
[1] 2023-02-16 14:45:23 正在检测和创建云盘文件夹: /apps/uploads/encrypted/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3r7a5D5Ev24-2A3LwN8RNqSk--
[2023-2-16 14:45:00.176] file path cache hit:  /apps/uploads/encrypted/ECRYPTFS_FNEK_ENCRYPTED.FWaaOgiEKqb9hEQ8tmF91WqTbE3-0.Xkia3r7a5D5Ev24-2A3LwN8RNqSk--
[2023-2-16 14:45:00.176] do request url: https://api.aliyundrive.com/v2/file/list
[2023-2-16 14:45:00.175] do request url: https://api.aliyundrive.com/v2/file/list
[3] 2023-02-16 14:45:23 文件上传结果：  耗时 1秒
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5ef094]

goroutine 103 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0x400053a8f0, 0x400037a480)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:369 +0x7b4
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0x4000eb61e0, 0x4000271bc0, 0x400000d1b8)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x5c
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x6c
```

**Comment by pda8888** [comment]
作者已经更新到0.2.6了

**Comment by MN2yFii** [comment]
> 作者已经更新到0.2.6了

看commit历史v0.2.6只修改了几次readme和修复了一个文件夹重名的问题。。。。。

**Comment by MN2yFii** [comment]
下面是用v0.2.6上传的日志，并发4，分片1m，其它设置没变。还是报无效内存地址错误。
```bash
[2023-2-18 08:51:40.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx
[2023-2-18 08:51:40.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx
[2023-2-18 08:51:40.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx
[2023-2-18 08:51:40.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx/xxxxx
[2023-2-18 08:51:40.506] do request url: https://api.aliyundrive.com/v2/file/list
[2023-2-18 08:51:40.642] file path cache hit:  /apps
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents/xxxx
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents/xxxx/xx
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx
[2023-2-18 08:51:40.642] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx
[2023-2-18 08:51:40.643] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx/xxxxx
[2023-2-18 08:51:40.643] do request url: https://api.aliyundrive.com/v2/file/list
[112] 2023-02-18 08:51:23 文件上传结果： 失败！检测同名文件失败,device session signature error 耗时 5秒
[2023-2-18 08:51:40.745] use config dir:  /home/xxxx/xxxx/xxxx/aliyunpan-v0.2.6-linux-arm64
[2023-2-18 08:51:40.746] 插件UploadFileFinishCallback调用成功
[117] 2023-02-18 08:51:23 准备上传: /mnt/xxxx/xxxx/data/documents/xxxx/xx/xxxx/xxxx/xxxx/xxxx => /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx/xxxx
[2023-2-18 08:51:40.746] [117] 2023-02-18 08:51:23 准备结束, 准备耗时 0秒
[113] 2023-02-18 08:51:23 正在计算文件SHA1: /mnt/xxxx/xxxx/data/documents/xxxx/xx/xxxx/xxxx/xxxx/xxxxx.txt
[2023-2-18 08:51:41.505] file path cache hit:  /apps
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents/xxxx
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx
[2023-2-18 08:51:41.505] file path cache hit:  /apps/uploads/data/documents/xxxx/xx/xxxx/xxxx/xxxx
[2023-2-18 08:51:41.505] do request url: https://api.aliyundrive.com/v2/file/list
[115] 2023-02-18 08:51:23 文件上传结果：  耗时 2秒
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x600458]

goroutine 353 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0x4000142a50, 0x4000bfcd00)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:371 +0x7e8
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0x4000bd0570, 0x40000a04b0, 0x4000264210)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x5c
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x6c
```

**Comment by wangyou233** [comment]
同样问题，更新版本得到了解决

**Comment by wangyou233** [comment]
> > 作者已经更新到0.2.6了
> 
> 看commit历史v0.2.6只修改了几次readme和修复了一个文件夹重名的问题。。。。。

可以尝试下

**Comment by MN2yFii** [comment]
> > > 作者已经更新到0.2.6了
> > 
> > 
> > 看commit历史v0.2.6只修改了几次readme和修复了一个文件夹重名的问题。。。。。
> 
> 可以尝试下

在4楼已经试了，还是同样报错。
```bash
[2023-2-18 08:51:40.745] use config dir:  /home/xxxx/xxxx/xxxx/aliyunpan-v0.2.6-linux-arm64
```

这个bug是有概率发生不是一定发生，我也试过上传成功。

**Comment by wangyou233** [comment]
> > > > 作者已经更新到0.2.6了
> > > 
> > > 
> > > 看commit历史v0.2.6只修改了几次readme和修复了一个文件夹重名的问题。。。。。
> > 
> > 
> > 可以尝试下
> 
> 在4楼已经试了，还是同样报错。
> 
> ```shell
> [2023-2-18 08:51:40.745] use config dir:  /home/xxxx/xxxx/xxxx/aliyunpan-v0.2.6-linux-arm64
> ```
> 
> 这个bug是有概率发生不是一定发生，我也试过用v0.2.1上传成功。

![image](https://user-images.githubusercontent.com/30244898/219880543-0ff8c85e-96f3-4d7c-8b65-cf0c6994b367.png)

奇怪，我更新完之后就没有这个错误了，我通过yum update aliyunpan 更新的

**Comment by wangyou233** [comment]
更新后，没这个错误了
![image](https://user-images.githubusercontent.com/30244898/219880775-bb2c19f9-6b1d-48d8-bc00-761c6c8a47db.png)

**Comment by DockerYumeko** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaf3a7a]

goroutine 40 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc0000d0000, 0xf1c9d8, 0xc000199640, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc0000d0000, 0xf1c9d8, 0xc000199640, 0xc00010e0e0, 0xc000317350)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d


aliyunpan -version
aliyunpan version v0.2.6

```

我这也是出现这个错误，版本0.26也有

**Comment by MN2yFii** [comment]
我好像找到原因了，但是不懂go不知道怎么修。
https://github.com/tickstep/aliyunpan/blob/c5a5cb906d9819b73e73c957687bcf4f785bfb1e/internal/functions/panupload/upload_task_unit.go#L355-L372
问题应该出现在L355调用了PanClient.FileInfoByPath，它有可能调用aliyunpan-api里面的PanClient.getFileInfoByPath然后调用。。。。直到PanClient.fileListReq。这个函数有可能返回<nil, ApiCodeNetError>或者<nil, ApiCodeFailed>。这时L357的if就会跳到else语句，然后L371的fe.FileId引发空指针。
上面这位朋友的报错信息中syncdrive/file_action_task.go也调用了PanClient.FileInfoByPath，可能也和这个问题有关。
但是昨天修完这个问题之后，测试了一下上传，接近有一万个文件失败，screen的翻页都翻不到头，看不到出错原因。

**Comment by xiaoyaofenfen** [comment]
> 我好像找到原因了，但是不懂go不知道怎么修。
> 
> https://github.com/tickstep/aliyunpan/blob/c5a5cb906d9819b73e73c957687bcf4f785bfb1e/internal/functions/panupload/upload_task_unit.go#L355-L372
> 
> 
> 问题应该出现在L355调用了PanClient.FileInfoByPath，它有可能调用aliyunpan-api里面的PanClient.getFileInfoByPath然后调用。。。。直到PanClient.fileListReq。这个函数有可能返回<nil, ApiCodeNetError>或者<nil, ApiCodeFailed>。这时L357的if就会跳到else语句，然后L371的fe.FileId引发空指针。
> 上面这位朋友的报错信息中syncdrive/file_action_task.go也调用了PanClient.FileInfoByPath，可能也和这个问题有关。
> 但是昨天修完这个问题之后，测试了一下上传，接近有一万个文件失败，screen的翻页都翻不到头，看不到出错原因。

确实是这里的问题，这里的逻辑不严谨。这里创建文件夹的时候是有失败的可能，例如网络，例如阿里API分控。我调整了一些逻辑，看看是否有改善。

**Comment by MN2yFii** [comment]
测试了commit cbf372bde0549fd6d8b26747e4a3a8e5c7c25a35 上传空指针的问题没再出现了。上传少量（100个）文件正常。但上传大量（1万个）文件，在添加完上传队列开始上传时就一直报错：`文件上传结果： 失败！检测同名文件失败,签名过期，需要更新签名密钥` 。试了扫二维码登录、15分钟update一次token、单线程上传都是同样的错误。不过和这个issue关系不大，先close了。
