### ISSUE TITLE
backup正常上传文件报错

### ISSUE THREAD

**Issue by kousyoukun** [tickstep/aliyunpan#25]
设备树莓派4B，经常上传到一半就报这个错，而且报错之前会长时间0KB/s

```
[2] 秒传失败，开始正常上传文件
[2] ↑ 181.56MB/314.13MB 288.04KB/s in 27m9s ............panic: runtime error: slice bounds out of range [:131072] with capacity 65536

goroutine 35080 [running]:
bufio.(*Reader).Read(0x240ac90, 0x4700000, 0x8000, 0x8000, 0xa6a9b570, 0x0, 0x3ff)
	/usr/local/go/src/bufio/bufio.go:238 +0x3e8
github.com/tickstep/aliyunpan/internal/file/uploader.(*bufioFileBlock).Read(0x1f88118, 0x4700000, 0x8000, 0x8000, 0x8000, 0x4700000, 0x1c80000)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/file/uploader/block.go:80 +0x38
io.(*LimitedReader).Read(0x2015e50, 0x4700000, 0x8000, 0x8000, 0x0, 0x468c00, 0xa6b5bf48)
	/usr/local/go/src/io/io.go:473 +0xb8
io.copyBuffer(0xa6b5bf48, 0x1dc7000, 0x502f6c, 0x2015e50, 0x4700000, 0x8000, 0x8000, 0x418b08, 0x435b80, 0x18e01, ...)
	/usr/local/go/src/io/io.go:423 +0xd8
io.Copy(...)
	/usr/local/go/src/io/io.go:382
net/http.persistConnWriter.ReadFrom(0x22fc3c0, 0x502f6c, 0x2015e50, 0xa6b5bf30, 0x22fc3c0, 0x418b01, 0x44f130)
	/usr/local/go/src/net/http/transport.go:1768 +0x68
bufio.(*Writer).ReadFrom(0x1c0b000, 0x502f6c, 0x2015e50, 0xa6c6e4a8, 0x1c0b000, 0x2015e01, 0x10)
	/usr/local/go/src/bufio/bufio.go:730 +0x31c
io.copyBuffer(0x502814, 0x1c0b000, 0x502f6c, 0x2015e50, 0x0, 0x0, 0x0, 0xa6c6e460, 0x0, 0x200, ...)
	/usr/local/go/src/io/io.go:409 +0x340
io.Copy(...)
	/usr/local/go/src/io/io.go:382
net/http.(*transferWriter).doBodyCopy(0x218e9b0, 0x502814, 0x1c0b000, 0x502f6c, 0x2015e50, 0x1dc7114, 0x1dc71d0, 0x1dc7114, 0x497350)
	/usr/local/go/src/net/http/transfer.go:409 +0x48
net/http.(*transferWriter).writeBody(0x218e9b0, 0x502814, 0x1c0b000, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:367 +0x6c8
net/http.(*Request).write(0x1cca700, 0x502814, 0x1c0b000, 0x0, 0x1c0b020, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:697 +0x5b8
net/http.(*persistConn).writeLoop(0x22fc3c0)
	/usr/local/go/src/net/http/transport.go:2385 +0x140
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1744 +0x9d0
```

**Comment by tickstep** [comment]
能开启Debug日志，复现下这个问题，然后把日志帮忙贴上来么

**Comment by kousyoukun** [comment]
```
[2021-11-15 19:06:06.312] upload file data chunk error  PartNotSequential
[2021-11-15 19:06:06.312] DEBUG: UPLOADER INFO: multiUpload worker upload file done
[2021-11-15 19:06:06.312] DEBUG: UPLOADER WARN: upload err: update data error, id: 2109
[2021-11-15 19:06:06.312] DEBUG: UPLOADER INFO: begin to upload part: 2110
[2021-11-15 19:06:06.312] do request url: https://bj29.cn-beijing.data.alicloudccp.com/v3F46yYX%2F1968987%2F61922f477149bd6cb39d4620a01108d2f39a842a%2F61922f4709dfc3f10a524695a9b77a4b82ca4f95?partNumber=2111&uploadId=0DA95E48B7C0431388F6EE0E8BC85D51&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1636973911&x-oss-signature=%2FRAqQ1LGZ8O6rU%2FuXJCLasljr7t0UoHIlsUxQiDzv%2FI%3D&x-oss-signature-version=OSS2
[2] ↑ 786.00MB/1.78GB 448.13KB/s in 1h7m25s ............[2021-11-15 19:06:06.544] 分片上传出错: 分片2110 => <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired.</Message>
  <RequestId>61923F1EBBBAD73531D368B0</RequestId>
  <HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
  <Expires>2021-11-15T10:58:31.000Z</Expires>
  <ServerTime>2021-11-15T11:06:06.000Z</ServerTime>
</Error>

[2021-11-15 19:06:06.544] upload file data chunk error  UrlExpired
[2021-11-15 19:06:06.545] do request url: https://api.aliyundrive.com/v2/file/get_upload_url
[2021-11-15 19:06:06.643] do request url: https://bj29.cn-beijing.data.alicloudccp.com/v3F46yYX%2F1968987%2F61922f477149bd6cb39d4620a01108d2f39a842a%2F61922f4709dfc3f10a524695a9b77a4b82ca4f95?partNumber=2111&uploadId=0DA95E48B7C0431388F6EE0E8BC85D51&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1636977966&x-oss-signature=bg9tCik%2FWKzngEw1%2FYS4n7CEEMZ%2BnwXy5BQe1FWjDQE%3D&x-oss-signature-version=OSS2
[2021-11-15 19:06:06.886] 分片上传出错: 分片2110 => <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>PartNotSequential</Code>
  <Message>For sequential multipart upload, you must upload or complete parts with sequential part number.</Message>
  <RequestId>61923F1E6649793338A19C7C</RequestId>
  <HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
  <PartNumber>2111</PartNumber>
</Error>

[2021-11-15 19:06:06.887] upload file data chunk error  PartNotSequential
[2021-11-15 19:06:06.887] DEBUG: UPLOADER INFO: multiUpload worker upload file done
[2021-11-15 19:06:06.887] DEBUG: UPLOADER WARN: upload err: update data error, id: 2110
[2021-11-15 19:06:06.887] DEBUG: UPLOADER INFO: begin to upload part: 2111
[2021-11-15 19:06:06.887] do request url: https://bj29.cn-beijing.data.alicloudccp.com/v3F46yYX%2F1968987%2F61922f477149bd6cb39d4620a01108d2f39a842a%2F61922f4709dfc3f10a524695a9b77a4b82ca4f95?partNumber=2112&uploadId=0DA95E48B7C0431388F6EE0E8BC85D51&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1636973911&x-oss-signature=884MA6lOnoIGf5IadrbImAboFZqzNtwP%2BlM%2FcABFQyI%3D&x-oss-signature-version=OSS2
[2021-11-15 19:06:07.130] 分片上传出错: 分片2111 => <?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AccessDenied</Code>
  <Message>Request has expired.</Message>
  <RequestId>61923F1F3040153338D90B24</RequestId>
  <HostId>bj29.cn-beijing.data.alicloudccp.com</HostId>
  <Expires>2021-11-15T10:58:31.000Z</Expires>
  <ServerTime>2021-11-15T11:06:07.000Z</ServerTime>
</Error>

[2021-11-15 19:06:07.130] upload file data chunk error  UrlExpired
[2021-11-15 19:06:07.130] do request url: https://api.aliyundrive.com/v2/file/get_upload_url
[2021-11-15 19:06:07.229] do request url: https://bj29.cn-beijing.data.alicloudccp.com/v3F46yYX%2F1968987%2F61922f477149bd6cb39d4620a01108d2f39a842a%2F61922f4709dfc3f10a524695a9b77a4b82ca4f95?partNumber=2112&uploadId=0DA95E48B7C0431388F6EE0E8BC85D51&x-oss-access-key-id=LTAIsE5mAn2F493Q&x-oss-expires=1636977967&x-oss-signature=DNMCu4jbYqrQiFJjIH2hZ03h2eSaKnOon8L160u6ZQU%3D&x-oss-signature-version=OSS2
[2] ↑ 786.00MB/1.78GB 288.15KB/s in 1h7m26s ............panic: runtime error: slice bounds out of range [:131072] with capacity 65536

goroutine 14934 [running]:
bufio.(*Reader).Read(0x167c090, 0x10380000, 0x8000, 0x8000, 0xa6ab1188, 0x0, 0x3ff)
        /usr/local/go/src/bufio/bufio.go:238 +0x3e8
github.com/tickstep/aliyunpan/internal/file/uploader.(*bufioFileBlock).Read(0x118c578, 0x10380000, 0x8000, 0x8000, 0x8000, 0x10380000, 0x1034480)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/file/uploader/block.go:80 +0x38
io.(*LimitedReader).Read(0x101a9990, 0x10380000, 0x8000, 0x8000, 0x0, 0x468c00, 0xa6ad8868)
        /usr/local/go/src/io/io.go:473 +0xb8
io.copyBuffer(0xa6ad8868, 0xff83200, 0x50314c, 0x101a9990, 0x10380000, 0x8000, 0x8000, 0x418b50, 0x435bc8, 0x18e01, ...)
        /usr/local/go/src/io/io.go:423 +0xd8
io.Copy(...)
        /usr/local/go/src/io/io.go:382
net/http.persistConnWriter.ReadFrom(0x1117c20, 0x50314c, 0x101a9990, 0xa6ad8850, 0x1117c20, 0x418b01, 0x44f1a8)
        /usr/local/go/src/net/http/transport.go:1768 +0x68
bufio.(*Writer).ReadFrom(0x1010dfa0, 0x50314c, 0x101a9990, 0xa6cf6ee8, 0x1010dfa0, 0x101a9901, 0x10)
        /usr/local/go/src/bufio/bufio.go:730 +0x31c
io.copyBuffer(0x5029f4, 0x1010dfa0, 0x50314c, 0x101a9990, 0x0, 0x0, 0x0, 0xa6cf6ea0, 0x0, 0x200, ...)
        /usr/local/go/src/io/io.go:409 +0x340
io.Copy(...)
        /usr/local/go/src/io/io.go:382
net/http.(*transferWriter).doBodyCopy(0x1009bea0, 0x5029f4, 0x1010dfa0, 0x50314c, 0x101a9990, 0xff83314, 0xff833d0, 0xff83314, 0x497488)
        /usr/local/go/src/net/http/transfer.go:409 +0x48
net/http.(*transferWriter).writeBody(0x1009bea0, 0x5029f4, 0x1010dfa0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:367 +0x6c8
net/http.(*Request).write(0xfd6dc00, 0x5029f4, 0x1010dfa0, 0x0, 0x1010dfc0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:697 +0x5b8
net/http.(*persistConn).writeLoop(0x1117c20)
        /usr/local/go/src/net/http/transport.go:2385 +0x140
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0x9d0
```

**Comment by oliverck** [comment]
+1 也遇到了这个情况

**Comment by tickstep** [comment]
可以试试v0.1.6 版本的sync命令进行备份
