### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sulyin** [tickstep/aliyunpan#258]
启动同步备份进程
备份配置文件：/home/programs/aliyunpan-v0.2.6-linux-386/sync_drive/sync_drive_config.json
链接类型：默认链接
下载并发：2
上传并发：5
下载分片大小：1.00MB
上传分片大小：10.00MB

启动同步任务
任务: 文档备份(6e62c4e7-44e9-4b57-b1e6-fb8******273)
同步模式: 备份本地文件（只上传）
本地目录: /home/aliyunupload
云盘目录: /aliyunupload

本命令不会退出，程序正在以非交互的方式运行。如需退出请借助运行环境提供的方式。
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x86095c2]

goroutine 14 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xa690100, 0x89c0dbc, 0xa951f40, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x19d2
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xa690100, 0x89c0dbc, 0xa951f40, 0xa726400, 0xa4be060)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x35
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x25f

**Comment by xiaoyaofenfen** [comment]
新版本同步已经优化很多，请在新版本中继续关注，感谢反馈
