### ISSUE TITLE
同步时报错 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by 123485k** [tickstep/aliyunpan#265]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaf3a7a]
                                              
goroutine 522 [running]:                                                                                                                                                                 
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc0004d4460, 0xf1c9d8, 0xc000096f80, 0x0, 0xc0001d1ce0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa                                                                     
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc0004d4460, 0xf1c9d8, 0xc000096f80, 0xc00037a0e0, 0xc0003c37d0)                 
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45                                                                   
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor                                                                              
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d
```

**Comment by huangjianye** [comment]
可以参考 issues #76

**Comment by 123485k** [comment]
我实在termux里面执行的，在zsh里面，应该有source /etc/profile这一步的

**Comment by xiaoyaofenfen** [comment]
版本太久远，在新版本程序再跟进下。感谢反馈
