### ISSUE TITLE
panic 报错

### ISSUE THREAD

**Issue by neoworld** [tickstep/aliyunpan#268]
`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x140 pc=0x8652f8b]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.parseDriveId(0x9d484d0, 0x2, 0x9e306f0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/command.go:70 +0x2b
github.com/tickstep/aliyunpan/internal/command.CmdUpload.func1(0x9d484d0, 0x0, 0x8f16420)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/upload.go:196 +0x191
github.com/urfave/cli.HandleAction(0x86d92a0, 0x8905bd0, 0x9d484d0, 0x9d484d0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0xd0
github.com/urfave/cli.Command.Run(0x87a87d2, 0x6, 0x0, 0x0, 0x9e2c7c8, 0x1, 0x1, 0x87b2b5d, 0x13, 0x9e17810, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x48f
github.com/urfave/cli.(*App).Run(0xa16b260, 0x9d0a000, 0x6, 0x6, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x673
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:634 +0xca7`

**Comment by xiaoyaofenfen** [comment]
版本太久远，在新版本程序再跟进下。感谢反馈
