### ISSUE TITLE
aliyunpan-sync 自动停止

### ISSUE THREAD

**Issue by czxinshui** [tickstep/aliyunpan#282]
aliyunpan-sync 启用一段时间就知道停止

**Comment by czxinshui** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xaf3a7a]

goroutine 2586 [running]:
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc00011e000, 0xf1c9d8, 0xc0000bad40, 0x8, 0xc0002c80c0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:101 +0x1dfa
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1(0xc00011e000, 0xf1c9d8, 0xc0000bad40, 0xc000302000, 0xc00034a510)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:819 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:818 +0x30d

**Comment by xiaoyaofenfen** [comment]
请在新版本中继续关注，感谢反馈
