### ISSUE TITLE
使用upload命令报错

### ISSUE THREAD

**Issue by klzw2233** [tickstep/aliyunpan#283]
aliyunpan:/ Unknown$ upload /root/minecraft_1.7.10.zip /minecraft

[0] 当前文件上传最大并发量为: 10, 上传分片大小为: 10.00MB
警告: 上传文件, 获取云盘路径 /minecraft 错误, device session signature error
[1] 加入上传队列: /root/minecraft_1.7.10.zip
[1] 2023-03-29 17:11:23 准备上传: /root/minecraft_1.7.10.zip => /minecraft/minecraft_1.7.10.zip
[1] 2023-03-29 17:11:23 正在检测和创建云盘文件夹: /minecraft
[1] 2023-03-29 17:11:23 文件上传结果：  耗时 1秒
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xae8039]

goroutine 37 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*UploadTaskUnit).Run(0xc0003e2000, 0xc0003dcb00)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload_task_unit.go:371 +0xa99
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc00016a390, 0xc000210270, 0xc0003ba2a0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:111 +0x62
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x7c

**Comment by xiaoyaofenfen** [comment]
新版本上传已经优化很多，请在新版本中继续关注，感谢反馈
