### ISSUE TITLE
aliyunpan 同步目录时报错

### ISSUE THREAD

**Issue by Ryan2009** [tickstep/aliyunpan#309]
执行命令行: 
aliyunpan sync start -ldir /opt/backup/ -pdir "/offical/backup20/" -mode "upload" -up 5 -ubs 10480
输出错误日志: 

本命令不会退出，程序正在以非交互的方式运行。如需退出请借助运行环境提供的方式。
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x190 pc=0xac33cd]

goroutine 24 [running]:
github.com/tickstep/bolt.(*DB).beginTx(0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/bolt@v1.3.3/db.go:470 +0x2d
github.com/tickstep/bolt.(*DB).Begin(0x0, 0x0, 0xcef8a2, 0x1, 0x0)
        /Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/bolt@v1.3.3/db.go:463 +0x6f
github.com/tickstep/aliyunpan/internal/syncdrive.(*BoltDb).GetFileList(0xc0001d02a0, 0xcef8a2, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/bolt_db.go:196 +0xfb
github.com/tickstep/aliyunpan/internal/syncdrive.(*SyncFileDbBolt).GetFileList(0xc0001d0260, 0xcf585b, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/sync_db_bolt.go:414 +0x185
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).getFromSyncDb(0xc0003040e0, 0xcf295d, 0x6, 0x0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:738 +0x41f
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor(0xc0003040e0, 0xf1c9d8, 0xc0000c0bc0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:812 +0x22d
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).Start
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:163 +0x165

**Comment by QiaolinLu** [comment]
我也遇到这个问题，请问老哥解决了吗

**Comment by Stephenhua** [comment]
我也遇到了这个问题， 请问解决了吗

**Comment by xiaoyaofenfen** [comment]
版本太久远，在新版本程序再跟进下
