### ISSUE TITLE
v0.2.7同步报错 error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by RyougiShiki-214** [tickstep/aliyunpan#318]
同步1000个文件，昨晚已经正常同步800个文件了，今天一看同步停止并报错。
重新同步仍然报错，重启系统也没有作用。

2023/06/30 10:59:24 bolt.Close(): funlock error: The handle is invalid.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0x190 pc=0x14ca4d4]

goroutine 102 [running]:
github.com/tickstep/bolt.(*DB).beginTx(0x0, 0x6e6b426154383771, 0x4f3055466e423225, 0x4667516567327548)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/bolt@v1.3.3/db.go:470 +0x34
github.com/tickstep/bolt.(*DB).Begin(0x0, 0x0, 0x16f9a82, 0x1, 0x7251456a346f454d)
	/Users/tickstep/Applications/go/pkg/mod/github.com/tickstep/bolt@v1.3.3/db.go:463 +0x75
github.com/tickstep/aliyunpan/internal/syncdrive.(*BoltDb).GetFileList(0xc0005366a0, 0x16f9a82, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/bolt_db.go:196 +0x10c
github.com/tickstep/aliyunpan/internal/syncdrive.(*SyncFileDbBolt).GetFileList(0xc0005b8120, 0x16ff9a6, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/sync_db_bolt.go:414 +0x18f
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).getFromSyncDb(0xc000650000, 0x16fcbea, 0x6, 0x0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:738 +0x41f
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor(0xc000650000, 0x1931fd8, 0xc00060bfc0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:812 +0x22d
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).Start
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:163 +0x165

**Comment by Stephenhua** [comment]
你好，请问你这个问题解决了吗？我现在也遇到了同样的问题

**Comment by RyougiShiki-214** [comment]
> 你好，请问你这个问题解决了吗？我现在也遇到了同样的问题

当时没有解决，放弃了。
