### ISSUE TITLE
用crontab执行报错，手工执行没问题

### ISSUE THREAD

**Issue by mikuQ** [tickstep/aliyunpan#356]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x390 pc=0xa9becc]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.parseDriveId(0xc00016e6e0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/command.go:70 +0x2c
github.com/tickstep/aliyunpan/internal/command.CmdUpload.func1(0xc00016e6e0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/upload.go:196 +0x18d
github.com/urfave/cli.HandleAction({0xb21300?, 0xd7be78?}, 0x6?)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x50
github.com/urfave/cli.Command.Run({{0xc088c1, 0x6}, {0x0, 0x0}, {0xc0002f29a0, 0x1, 0x1}, {0xc12d53, 0x13}, {0xc0002b7810, ...}, ...}, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x67b
github.com/urfave/cli.(*App).Run(0xc000116380, {0xc000034080, 0x4, 0x4})
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0xbc7
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:665 +0x18fb

**Comment by mikuQ** [comment]
解决了，需要在脚本开头加载环境变量。
 . /etc/profile
. ~/.bash_profile
