### ISSUE TITLE
树莓派上运行很难保持登录状态

### ISSUE THREAD

**Issue by Crazygay12138** [tickstep/aliyunpan#413]
尝试在在树莓派上运行24小时监控和下载脚本，上传一次后只过了2分钟再次执行上传就跳出下面这个提示了：

`
尝试登录失败，请使用 login 命令进行重新登录
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x390 pc=0x5faf0c]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.parseDriveId(0x40001f0580)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/command.go:57 +0x2c
github.com/tickstep/aliyunpan/internal/command.CmdDownload.func1(0x40001f0580)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/download.go:136 +0x168
github.com/urfave/cli.HandleAction({0x688c20?, 0x8e4af8?}, 0x8?)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x58
github.com/urfave/cli.Command.Run({{0x7734f0, 0x8}, {0x0, 0x0}, {0x4000217c30, 0x1, 0x1}, {0x77bdc6, 0x13}, {0x40001e80a0, ...}, ...}, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x500
github.com/urfave/cli.(*App).Run(0x400022c000, {0x40000b6000, 0x7, 0x7})
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x820
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:681 +0x1470
`

然后得再次登录，并且还要登录好几次才行

**Comment by xiaoyaofenfen** [comment]
开debug日志看看哪里报错。同时确认下配置文件权限是否有问题

**Comment by Crazygay12138** [comment]
> 开debug日志看看哪里报错。同时确认下配置文件权限是否有问题

`
[2024-4-15 21:59:48.177] use config dir:  /home/johnp/aliyunpan
[2024-4-15 21:59:48.178] use config dir:  /home/johnp/aliyunpan
[2024-4-15 21:59:48.181] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
[2024-4-15 21:59:48.351] get drive info error  Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp 47.88.74.38:443: connect: connection refused
[2024-4-15 21:59:48.351] setup user error
[2024-4-15 21:59:48.351] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
[2024-4-15 21:59:48.529] get drive info error  Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp 47.88.74.38:443: connect: connection refused
[2024-4-15 21:59:48.529] 尝试登录失败:  Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp 47.88.74.38:443: connect: connection refused
尝试登录失败，请使用 login 命令进行重新登录
[2024-4-15 21:59:48.531] do request url: https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo
[2024-4-15 21:59:48.696] get drive info error  Post "https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp 47.88.74.38:443: connect: connection refused
[2024-4-15 21:59:48.696] setup user error
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x390 pc=0x5faf0c]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.parseDriveId(0x40001fac60)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/command.go:57 +0x2c
github.com/tickstep/aliyunpan/internal/command.CmdDownload.func1(0x40001fac60)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/download.go:136 +0x168
github.com/urfave/cli.HandleAction({0x688c20?, 0x8e4af8?}, 0x8?)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x58
github.com/urfave/cli.Command.Run({{0x7734f0, 0x8}, {0x0, 0x0}, {0x4000213b00, 0x1, 0x1}, {0x77bdc6, 0x13}, {0x40001fc460, ...}, ...}, ...)
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x500
github.com/urfave/cli.(*App).Run(0x4000146380, {0x4000030070, 0x7, 0x7})
        /Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x820
main.main()
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:681 +0x1470
`

**Comment by xiaoyaofenfen** [comment]
"https://openapi.alipan.com/adrive/v1.0/user/getDriveInfo": dial tcp 47.88.74.38:443: connect: connection refused

你这是阿里官网都连不上了啊

**Comment by huanranchen** [comment]
(I would like to make a shameless declaration once again to make up for my previous mistakes.) All the experiments for RDC and Likelihood Maximization (N) were conducted using the EDM checkpoint, and this part is not an issue.
All the experiments in the paper "Your Diffusion Model is Secretly a Certifiably Robust Classifier" were also performed using the EDM checkpoint. The paper achieved state-of-the-art certified robustness, demonstrating that the robustness of the diffusion classifier is genuine and not overestimated due to insufficient attacks.
