### ISSUE TITLE
window 11 64 后台运行数组越界（最新版）希望可以有容错机制，可以跳过不退出

### ISSUE THREAD

**Issue by inwikipedia** [tickstep/aliyunpan#441]
panic: runtime error: index out of range [0] with length 0

goroutine 10107 [running]:
github.com/tickstep/aliyunpan/internal/functions/panupload.(*PanUpload).UploadFile(0xc001543be8, {0xc007706570?, 0x6?}, 0x0, 0xc0001c1480?, 0x0?, {0x18ccf890fb8, 0xc007706590}, 0xc0000b88c0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/panupload/upload.go:78 +0x74d
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).uploadFile(0xc0010d6000, {0xcb1f10, 0xc000218960})
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:627 +0x1ad2
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTask).DoAction(0xc0010d6000, {0xcb1f10, 0xc000218960})
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task.go:66 +0x175
github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor.func1()
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:557 +0x45
created by github.com/tickstep/aliyunpan/internal/syncdrive.(*FileActionTaskManager).fileActionTaskExecutor
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/syncdrive/file_action_task_mgr.go:556 +0x30f
![image](https://github.com/user-attachments/assets/f04a4725-c1b2-4293-b986-f5f418563442)
![image](https://github.com/user-attachments/assets/534b097c-c076-46fb-9ce5-c91bbc66dfff)
![image](https://github.com/user-attachments/assets/89bbb44e-c6a1-4fe2-ac3e-7574d6fd168b)

![image](https://github.com/user-attachments/assets/25dbfb80-219e-48ca-848b-b22b7e6d67da)

**Comment by xiaoyaofenfen** [comment]
这看不出来问题，你可以先不要后台启动，先直接sync命令启动并打开debug日志，然后看看是哪里报错导致启动失败
