### ISSUE TITLE
上传总是出错

### ISSUE THREAD

**Issue by LondyGhost** [tickstep/aliyunpan#66]
[1] ↑ 7.85GB/11.23GB 1.26MB/s(1.26MB/s) in 59m56s ............panic: runtime error: slice bounds out of range [:131072] with capacity 65536
goroutine 1780 [running]:
bufio.(*Reader).Read(0xc0001ff620, 0xc0067d4000, 0x8000, 0x8000, 0x1a7e4e10a28, 0xc000055987, 0xc0067d4000)
        /usr/local/go/src/bufio/bufio.go:238 +0x3da
github.com/tickstep/aliyunpan/internal/file/uploader.(*bufioFileBlock).Read(0xc0001e6a10, 0xc0067d4000, 0x8000, 0x8000, 0x1a7e4e10a28, 0x8000, 0xc0067d4000)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/file/uploader/block.go:82 +0x54
io.(*LimitedReader).Read(0xc00009b5a8, 0xc0067d4000, 0x8000, 0x8000, 0x0, 0xc000008000, 0x8)
        /usr/local/go/src/io/io.go:473 +0x6f
io.copyBuffer(0x1a7ea955168, 0xc0001baa80, 0xadcb80, 0xc00009b5a8, 0xc0067d4000, 0x8000, 0x8000, 0x9bfea0, 0xdda901, 0x1a7ea955148)
        /usr/local/go/src/io/io.go:423 +0x12c
io.Copy(...)
        /usr/local/go/src/io/io.go:382
net/http.persistConnWriter.ReadFrom(0xc0000a87e0, 0xadcb80, 0xc00009b5a8, 0x1a7ea955148, 0xc0000a87e0, 0x63f101)
        /usr/local/go/src/net/http/transport.go:1768 +0x8c
bufio.(*Writer).ReadFrom(0xc00002d3c0, 0xadcb80, 0xc00009b5a8, 0x1a7ea0e40a8, 0xc00002d3c0, 0x1a7ea0e4001)
        /usr/local/go/src/bufio/bufio.go:730 +0x37e
io.copyBuffer(0xadbee0, 0xc00002d3c0, 0xadcb80, 0xc00009b5a8, 0x0, 0x0, 0x0, 0xc000055c38, 0x41e87f, 0x18)
        /usr/local/go/src/io/io.go:409 +0x357
io.Copy(...)
        /usr/local/go/src/io/io.go:382
net/http.(*transferWriter).doBodyCopy(0xc0000cab40, 0xadbee0, 0xc00002d3c0, 0xadcb80, 0xc00009b5a8, 0x7239d9, 0xc0001baa80, 0xc0067d2000)
        /usr/local/go/src/net/http/transfer.go:409 +0x71
net/http.(*transferWriter).writeBody(0xc0000cab40, 0xadbee0, 0xc00002d3c0, 0x0, 0x0)
        /usr/local/go/src/net/http/transfer.go:367 +0x817
net/http.(*Request).write(0xc0003a0b00, 0xadbee0, 0xc00002d3c0, 0x0, 0xc00025d6e0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/request.go:697 +0x7e6
net/http.(*persistConn).writeLoop(0xc0000a87e0)
        /usr/local/go/src/net/http/transport.go:2385 +0x1aa
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1744 +0xcbc

然后重新执行upload 上传任务就无法执行了

 u -norapid -ow D:\天翼云盘下载\中国医生.mkv /

[0] 当前文件上传最大并发量为: 10, 上传分片大小为: 10.00MB
[1] 加入上传队列: D:\天翼云盘下载\中国医生.mkv
[1] 2022-03-05 00:00:22 准备上传: D:\天翼云盘下载\中国医生.mkv => /中国医生.mkv
[1] 2022-03-05 00:00:22 已经禁用秒传检测，直接上传
[1] 2022-03-05 00:00:22 文件上传结果：  耗时 4秒

上传结束, 时间: 4秒, 数据总量: 0B
以下文件上传失败:
  1  D:\天翼云盘下载\中国医生.mkv

仅此为例，大部分大于10G的文件都会如此

**Comment by xiaoyaofenfen** [comment]
请在新版本程序再跟进下。感谢反馈
