### ISSUE TITLE
logout报错

### ISSUE THREAD

**Issue by PHCSJC** [tickstep/aliyunpan#82]
Token过期，需要重新登录
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8f08cd]

goroutine 1 [running]:
github.com/tickstep/aliyunpan/internal/command.CmdLogout.func1(0xc0000df760, 0xdb2160, 0xc0004695d0)
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/command/login.go:110 +0x26d
github.com/urfave/cli.HandleAction(0x953fc0, 0xa311f8, 0xc0000df760, 0xc0000df760, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:523 +0x105
github.com/urfave/cli.Command.Run(0xa05c43, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xa0df10, 0x12, 0x0, ...)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/command.go:174 +0x579
github.com/urfave/cli.(*App).Run(0xc000196380, 0xc0000b0000, 0x2, 0x2, 0x0, 0x0)
	/Users/tickstep/Applications/go/pkg/mod/github.com/urfave/cli@v1.21.1-0.20190817182405-23c83030263f/app.go:276 +0x7e8
main.main()
	/Users/tickstep/Documents/Workspace/go/projects/aliyunpan/main.go:618 +0x187e

**Comment by PHCSJC** [comment]
重新登录也不行，还是报token过期，现在是退出不了，也重新登录不了，怎么解决呢？大佬？
