### ISSUE TITLE
似乎不支持某些文件夹下载

### ISSUE THREAD

**Issue by summerkirakira** [tickstep/aliyunpan#93]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/56951617/169597580-cff53a74-b69e-4485-80a0-f629d6dcc25e.png">
此路径无法进入，显示为文件不存在
且下载时会报错

```
[0] 当前文件下载最大并发量为: 5, 下载缓存为: 64.00KB

[1] 加入下载队列: /动漫/《爱，死亡和机器人》S01-S03全 4K/1080P★
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xab9b59]

goroutine 835 [running]:
github.com/tickstep/aliyunpan/internal/functions/pandownload.(*DownloadTaskUnit).pluginCallback(0xc00027c820, 0xc88ab5, 0x4)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/pandownload/download_task_unit.go:354 +0x99
github.com/tickstep/aliyunpan/internal/functions/pandownload.(*DownloadTaskUnit).OnFailed(0xc00027c820, 0xc0000c44c0)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/functions/pandownload/download_task_unit.go:339 +0x55
github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute.func1(0xc00040c990, 0xc00040c6f0, 0xc000627f08)
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:155 +0x1ec
created by github.com/tickstep/aliyunpan/internal/taskframework.(*TaskExecutor).Execute
        /Users/tickstep/Documents/Workspace/go/projects/aliyunpan/internal/taskframework/executor.go:108 +0x7c
```

但在阿里云盘网页中将内部文件移出即可下载，猜测是某种风控机制。

**Comment by xiaoyaofenfen** [comment]
请在新版本程序再跟进下。感谢反馈
